TRAIN:
  # ENABLE: True
  DATASET: fmf_vicu
  BATCH_SIZE: 64
  LR: 0.0001
  GRAD_CLIP: 1.
  TOTAL_STEPS: 100000
  WARMUP: 5
  EMA_DECAY: 0.9999
  SAVE_STEP: 5000
DATA:
  MAT_FILES: './data/FMFBenchmarkV1'
  NUM_FRAMES: 10
  SAMPLING_RATE: 18
  IMAGE_SIZE: 64
  CURRENT_SECONDS: 120
  CURRENT_PATCH_DIMS: 3
  MODE: 'train'
SOLVER:
  BASE_LR: 0.0005
  LR_POLICY: step
  COSINE_END_LR: 0.
  STEPS: [20]
  MAX_EPOCH: 30
MODEL:
  T: 1000
  CONDITION_IN: 3
  EMBED_DIM: 128
  CHANNEL_MULT: [1, 2, 2, 2]
  ATTN_BLOCK: [1]
  NUM_RES_BLOCKS: 2
  DROPOUT: 0.1
  MODEL_NAME: vit_for_vicu
  NUM_CLASSES: 2
  IMAGE_PATCH_SIZE: 8
  FRAME_PATCH_SIZE: 2
  ADDITIONAL_TOKENS: True
  PRETRAINED: './state_dict_vicu_cls.pth'
  PARALLEL: False
DIFFUSION:
  BETA_1: 0.0001
  BETA_T: 0.02
  MEAN_TYPE: 'epsilon'
  VAR_TYPE: 'fixedlarge'
  SAMPLE_SIZE: 64
  SAMPLE_STEP: 5000
TEST:
  MODE: 'l2'
  DATASET: fmf_vicu
  BATCH_SIZE: 64
  EVAL_STEP: 50000
  NUM_IMAGES: 10
  FID_USE_TORCH: False
  FID_CACHE: './stats/ffm.train.npz'
DATA_LOADER:
  NUM_WORKERS: 1
  PIN_MEMORY: True
COMMON:
  LOGDIR: './logs/DDPM_FFM_EPS'
OUTPUT_DIR: ''
PRINT_FREQ: 100
TASK: segmentation
